CREATE TABLE Worker
(
  WorkerID INT GENERATED BY DEFAULT AS IDENTITY,
  FirstName VARCHAR2(30) NOT NULL,
  LastName VARCHAR2(30) NOT NULL,
  StartDate DATE NOT NULL,
  PRIMARY KEY (WorkerID)
);

ALTER TABLE Staff_Member
ADD WorkerID INT;

BEGIN
  FOR rec IN (SELECT FirstName, LastName, StartDate FROM Staff_Member) LOOP
    INSERT INTO Worker (FirstName, LastName, StartDate)
    VALUES (rec.FirstName, rec.LastName, rec.StartDate);
  END LOOP;
END;
/

BEGIN
  FOR rec IN (SELECT SID, FirstName, LastName, StartDate FROM Staff_Member) LOOP
    UPDATE Staff_Member
    SET WorkerID = (SELECT WorkerID FROM Worker WHERE Worker.FirstName = rec.FirstName AND Worker.LastName = rec.LastName AND Worker.StartDate = rec.StartDate)
    WHERE SID = rec.SID;
  END LOOP;
END;
/

ALTER TABLE Staff_Member
ADD CONSTRAINT fk_worker_staff_member
FOREIGN KEY (WorkerID) REFERENCES Worker(WorkerID);

ALTER TABLE Doctor
ADD WorkerID INT;

BEGIN
  FOR rec IN (SELECT FirstName, LastName, StartDate FROM Doctor) LOOP
    INSERT INTO Worker (FirstName, LastName, StartDate)
    VALUES (rec.FirstName, rec.LastName, rec.StartDate);
  END LOOP;
END;
/

BEGIN
  FOR rec IN (SELECT DoctorID, FirstName, LastName, StartDate FROM Doctor) LOOP
    UPDATE Doctor
    SET WorkerID = (SELECT WorkerID FROM Worker WHERE Worker.FirstName = rec.FirstName AND Worker.LastName = rec.LastName AND Worker.StartDate = rec.StartDate)
    WHERE DoctorID = rec.DoctorID;
  END LOOP;
END;
/

ALTER TABLE Doctor
ADD CONSTRAINT fk_worker_doctor
FOREIGN KEY (WorkerID) REFERENCES Worker(WorkerID);

ALTER TABLE Nurse
ADD WorkerID INT;

BEGIN
  FOR rec IN (SELECT FirstName, LastName, StartDate FROM Nurse) LOOP
    INSERT INTO Worker (FirstName, LastName, StartDate)
    VALUES (rec.FirstName, rec.LastName, rec.StartDate);
  END LOOP;
END;
/

BEGIN
  FOR rec IN (SELECT NurseID, FirstName, LastName, StartDate FROM Nurse) LOOP
    UPDATE Nurse
    SET WorkerID = (SELECT WorkerID FROM Worker WHERE Worker.FirstName = rec.FirstName AND Worker.LastName = rec.LastName AND Worker.StartDate = rec.StartDate)
    WHERE NurseID = rec.NurseID;
  END LOOP;
END;
/

ALTER TABLE Nurse
ADD CONSTRAINT fk_worker_nurse
FOREIGN KEY (WorkerID) REFERENCES Worker(WorkerID);
